services:
  - type: web
    name: plataforma-reserva-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false   # la definís en la UI de Render
      - key: ENV
        value: production
    healthCheckPath: /

  - type: web
    name: plataforma-reserva-frontend
    env: node
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://plataforma-reserva-backend.onrender.com
